version: "3.8"
services:
  pg:
    image: postgres:15
    container_name: pg-local
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
