spring:
  config:
    import: optional:application-secret.yml

  application:
    name: stamp

  profiles:
    active: dev # ← 이건 local에서만 사용하고, ci/prod에서는 override 할 수 있도록

  datasource:
    url: jdbc:h2:mem:stampdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
