spring:
  application:
    name: stamp

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:stampdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
